#!/usr/bin/python3

import fcntl
import os
import struct
import sys

# this is the PGP wordl ist: https://en.wikipedia.org/wiki/PGP_word_list
words = [
    {'left': u'aardvark', 'right': u'adroitness'},
    {'left': u'absurd', 'right': u'adviser'},
    {'left': u'accrue', 'right': u'aftermath'},
    {'left': u'acme', 'right': u'aggregate'},
    {'left': u'adrift', 'right': u'alkali'},
    {'left': u'adult', 'right': u'almighty'},
    {'left': u'afflict', 'right': u'amulet'},
    {'left': u'ahead', 'right': u'amusement'},
    {'left': u'aimless', 'right': u'antenna'},
    {'left': u'algol', 'right': u'applicant'},
    {'left': u'allow', 'right': u'apollo'},
    {'left': u'alone', 'right': u'armistice'},
    {'left': u'ammo', 'right': u'article'},
    {'left': u'ancient', 'right': u'asteroid'},
    {'left': u'apple', 'right': u'atlantic'},
    {'left': u'artist', 'right': u'atmosphere'},
    {'left': u'assume', 'right': u'autopsy'},
    {'left': u'athens', 'right': u'babylon'},
    {'left': u'atlas', 'right': u'backwater'},
    {'left': u'aztec', 'right': u'barbecue'},
    {'left': u'baboon', 'right': u'belowground'},
    {'left': u'backfield', 'right': u'bifocals'},
    {'left': u'backward', 'right': u'bodyguard'},
    {'left': u'banjo', 'right': u'bookseller'},
    {'left': u'beaming', 'right': u'borderline'},
    {'left': u'bedlamp', 'right': u'bottomless'},
    {'left': u'beehive', 'right': u'bradbury'},
    {'left': u'beeswax', 'right': u'bravado'},
    {'left': u'befriend', 'right': u'brazilian'},
    {'left': u'belfast', 'right': u'breakaway'},
    {'left': u'berserk', 'right': u'burlington'},
    {'left': u'billiard', 'right': u'businessman'},
    {'left': u'bison', 'right': u'butterfat'},
    {'left': u'blackjack', 'right': u'camelot'},
    {'left': u'blockade', 'right': u'candidate'},
    {'left': u'blowtorch', 'right': u'cannonball'},
    {'left': u'bluebird', 'right': u'capricorn'},
    {'left': u'bombast', 'right': u'caravan'},
    {'left': u'bookshelf', 'right': u'caretaker'},
    {'left': u'brackish', 'right': u'celebrate'},
    {'left': u'breadline', 'right': u'cellulose'},
    {'left': u'breakup', 'right': u'certify'},
    {'left': u'brickyard', 'right': u'chambermaid'},
    {'left': u'briefcase', 'right': u'cherokee'},
    {'left': u'burbank', 'right': u'chicago'},
    {'left': u'button', 'right': u'clergyman'},
    {'left': u'buzzard', 'right': u'coherence'},
    {'left': u'cement', 'right': u'combustion'},
    {'left': u'chairlift', 'right': u'commando'},
    {'left': u'chatter', 'right': u'company'},
    {'left': u'checkup', 'right': u'component'},
    {'left': u'chisel', 'right': u'concurrent'},
    {'left': u'choking', 'right': u'confidence'},
    {'left': u'chopper', 'right': u'conformist'},
    {'left': u'christmas', 'right': u'congregate'},
    {'left': u'clamshell', 'right': u'consensus'},
    {'left': u'classic', 'right': u'consulting'},
    {'left': u'classroom', 'right': u'corporate'},
    {'left': u'cleanup', 'right': u'corrosion'},
    {'left': u'clockwork', 'right': u'councilman'},
    {'left': u'cobra', 'right': u'crossover'},
    {'left': u'commence', 'right': u'crucifix'},
    {'left': u'concert', 'right': u'cumbersome'},
    {'left': u'cowbell', 'right': u'customer'},
    {'left': u'crackdown', 'right': u'dakota'},
    {'left': u'cranky', 'right': u'decadence'},
    {'left': u'crowfoot', 'right': u'december'},
    {'left': u'crucial', 'right': u'decimal'},
    {'left': u'crumpled', 'right': u'designing'},
    {'left': u'crusade', 'right': u'detector'},
    {'left': u'cubic', 'right': u'detergent'},
    {'left': u'dashboard', 'right': u'determine'},
    {'left': u'deadbolt', 'right': u'dictator'},
    {'left': u'deckhand', 'right': u'dinosaur'},
    {'left': u'dogsled', 'right': u'direction'},
    {'left': u'dragnet', 'right': u'disable'},
    {'left': u'drainage', 'right': u'disbelief'},
    {'left': u'dreadful', 'right': u'disruptive'},
    {'left': u'drifter', 'right': u'distortion'},
    {'left': u'dropper', 'right': u'document'},
    {'left': u'drumbeat', 'right': u'embezzle'},
    {'left': u'drunken', 'right': u'enchanting'},
    {'left': u'dupont', 'right': u'enrollment'},
    {'left': u'dwelling', 'right': u'enterprise'},
    {'left': u'eating', 'right': u'equation'},
    {'left': u'edict', 'right': u'equipment'},
    {'left': u'egghead', 'right': u'escapade'},
    {'left': u'eightball', 'right': u'eskimo'},
    {'left': u'endorse', 'right': u'everyday'},
    {'left': u'endow', 'right': u'examine'},
    {'left': u'enlist', 'right': u'existence'},
    {'left': u'erase', 'right': u'exodus'},
    {'left': u'escape', 'right': u'fascinate'},
    {'left': u'exceed', 'right': u'filament'},
    {'left': u'eyeglass', 'right': u'finicky'},
    {'left': u'eyetooth', 'right': u'forever'},
    {'left': u'facial', 'right': u'fortitude'},
    {'left': u'fallout', 'right': u'frequency'},
    {'left': u'flagpole', 'right': u'gadgetry'},
    {'left': u'flatfoot', 'right': u'galveston'},
    {'left': u'flytrap', 'right': u'getaway'},
    {'left': u'fracture', 'right': u'glossary'},
    {'left': u'framework', 'right': u'gossamer'},
    {'left': u'freedom', 'right': u'graduate'},
    {'left': u'frighten', 'right': u'gravity'},
    {'left': u'gazelle', 'right': u'guitarist'},
    {'left': u'geiger', 'right': u'hamburger'},
    {'left': u'glitter', 'right': u'hamilton'},
    {'left': u'glucose', 'right': u'handiwork'},
    {'left': u'goggles', 'right': u'hazardous'},
    {'left': u'goldfish', 'right': u'headwaters'},
    {'left': u'gremlin', 'right': u'hemisphere'},
    {'left': u'guidance', 'right': u'hesitate'},
    {'left': u'hamlet', 'right': u'hideaway'},
    {'left': u'highchair', 'right': u'holiness'},
    {'left': u'hockey', 'right': u'hurricane'},
    {'left': u'indoors', 'right': u'hydraulic'},
    {'left': u'indulge', 'right': u'impartial'},
    {'left': u'inverse', 'right': u'impetus'},
    {'left': u'involve', 'right': u'inception'},
    {'left': u'island', 'right': u'indigo'},
    {'left': u'jawbone', 'right': u'inertia'},
    {'left': u'keyboard', 'right': u'infancy'},
    {'left': u'kickoff', 'right': u'inferno'},
    {'left': u'kiwi', 'right': u'informant'},
    {'left': u'klaxon', 'right': u'insincere'},
    {'left': u'locale', 'right': u'insurgent'},
    {'left': u'lockup', 'right': u'integrate'},
    {'left': u'merit', 'right': u'intention'},
    {'left': u'minnow', 'right': u'inventive'},
    {'left': u'miser', 'right': u'istanbul'},
    {'left': u'mohawk', 'right': u'jamaica'},
    {'left': u'mural', 'right': u'jupiter'},
    {'left': u'music', 'right': u'leprosy'},
    {'left': u'necklace', 'right': u'letterhead'},
    {'left': u'neptune', 'right': u'liberty'},
    {'left': u'newborn', 'right': u'maritime'},
    {'left': u'nightbird', 'right': u'matchmaker'},
    {'left': u'oakland', 'right': u'maverick'},
    {'left': u'obtuse', 'right': u'medusa'},
    {'left': u'offload', 'right': u'megaton'},
    {'left': u'optic', 'right': u'microscope'},
    {'left': u'orca', 'right': u'microwave'},
    {'left': u'payday', 'right': u'midsummer'},
    {'left': u'peachy', 'right': u'millionaire'},
    {'left': u'pheasant', 'right': u'miracle'},
    {'left': u'physique', 'right': u'misnomer'},
    {'left': u'playhouse', 'right': u'molasses'},
    {'left': u'preclude', 'right': u'montana'},
    {'left': u'prefer', 'right': u'monument'},
    {'left': u'preshrunk', 'right': u'mosquito'},
    {'left': u'printer', 'right': u'narrative'},
    {'left': u'prowler', 'right': u'nebula'},
    {'left': u'pupil', 'right': u'newsletter'},
    {'left': u'puppy', 'right': u'norwegian'},
    {'left': u'python', 'right': u'october'},
    {'left': u'quadrant', 'right': u'ohio'},
    {'left': u'quiver', 'right': u'onlooker'},
    {'left': u'quota', 'right': u'opulent'},
    {'left': u'ragtime', 'right': u'orlando'},
    {'left': u'ratchet', 'right': u'outfielder'},
    {'left': u'rebirth', 'right': u'pacific'},
    {'left': u'reform', 'right': u'pandemic'},
    {'left': u'regain', 'right': u'pandora'},
    {'left': u'reindeer', 'right': u'paperweight'},
    {'left': u'rematch', 'right': u'paragon'},
    {'left': u'repay', 'right': u'paragraph'},
    {'left': u'retouch', 'right': u'paramount'},
    {'left': u'revenge', 'right': u'passenger'},
    {'left': u'reward', 'right': u'pedigree'},
    {'left': u'rhythm', 'right': u'pegasus'},
    {'left': u'ribcage', 'right': u'penetrate'},
    {'left': u'ringbolt', 'right': u'perceptive'},
    {'left': u'robust', 'right': u'performance'},
    {'left': u'rocker', 'right': u'pharmacy'},
    {'left': u'ruffled', 'right': u'phonetic'},
    {'left': u'sailboat', 'right': u'photograph'},
    {'left': u'sawdust', 'right': u'pioneer'},
    {'left': u'scallion', 'right': u'pocketful'},
    {'left': u'scenic', 'right': u'politeness'},
    {'left': u'scorecard', 'right': u'positive'},
    {'left': u'scotland', 'right': u'potato'},
    {'left': u'seabird', 'right': u'processor'},
    {'left': u'select', 'right': u'provincial'},
    {'left': u'sentence', 'right': u'proximate'},
    {'left': u'shadow', 'right': u'puberty'},
    {'left': u'shamrock', 'right': u'publisher'},
    {'left': u'showgirl', 'right': u'pyramid'},
    {'left': u'skullcap', 'right': u'quantity'},
    {'left': u'skydive', 'right': u'racketeer'},
    {'left': u'slingshot', 'right': u'rebellion'},
    {'left': u'slowdown', 'right': u'recipe'},
    {'left': u'snapline', 'right': u'recover'},
    {'left': u'snapshot', 'right': u'repellent'},
    {'left': u'snowcap', 'right': u'replica'},
    {'left': u'snowslide', 'right': u'reproduce'},
    {'left': u'solo', 'right': u'resistor'},
    {'left': u'southward', 'right': u'responsive'},
    {'left': u'soybean', 'right': u'retraction'},
    {'left': u'spaniel', 'right': u'retrieval'},
    {'left': u'spearhead', 'right': u'retrospect'},
    {'left': u'spellbind', 'right': u'revenue'},
    {'left': u'spheroid', 'right': u'revival'},
    {'left': u'spigot', 'right': u'revolver'},
    {'left': u'spindle', 'right': u'sandalwood'},
    {'left': u'spyglass', 'right': u'sardonic'},
    {'left': u'stagehand', 'right': u'saturday'},
    {'left': u'stagnate', 'right': u'savagery'},
    {'left': u'stairway', 'right': u'scavenger'},
    {'left': u'standard', 'right': u'sensation'},
    {'left': u'stapler', 'right': u'sociable'},
    {'left': u'steamship', 'right': u'souvenir'},
    {'left': u'sterling', 'right': u'specialist'},
    {'left': u'stockman', 'right': u'speculate'},
    {'left': u'stopwatch', 'right': u'stethoscope'},
    {'left': u'stormy', 'right': u'stupendous'},
    {'left': u'sugar', 'right': u'supportive'},
    {'left': u'surmount', 'right': u'surrender'},
    {'left': u'suspense', 'right': u'suspicious'},
    {'left': u'sweatband', 'right': u'sympathy'},
    {'left': u'swelter', 'right': u'tambourine'},
    {'left': u'tactics', 'right': u'telephone'},
    {'left': u'talon', 'right': u'therapist'},
    {'left': u'tapeworm', 'right': u'tobacco'},
    {'left': u'tempest', 'right': u'tolerance'},
    {'left': u'tiger', 'right': u'tomorrow'},
    {'left': u'tissue', 'right': u'torpedo'},
    {'left': u'tonic', 'right': u'tradition'},
    {'left': u'topmost', 'right': u'travesty'},
    {'left': u'tracker', 'right': u'trombonist'},
    {'left': u'transit', 'right': u'truncated'},
    {'left': u'trauma', 'right': u'typewriter'},
    {'left': u'treadmill', 'right': u'ultimate'},
    {'left': u'trojan', 'right': u'undaunted'},
    {'left': u'trouble', 'right': u'underfoot'},
    {'left': u'tumor', 'right': u'unicorn'},
    {'left': u'tunnel', 'right': u'unify'},
    {'left': u'tycoon', 'right': u'universe'},
    {'left': u'uncut', 'right': u'unravel'},
    {'left': u'unearth', 'right': u'upcoming'},
    {'left': u'unwind', 'right': u'vacancy'},
    {'left': u'uproot', 'right': u'vagabond'},
    {'left': u'upset', 'right': u'vertigo'},
    {'left': u'upshot', 'right': u'virginia'},
    {'left': u'vapor', 'right': u'visitor'},
    {'left': u'village', 'right': u'vocalist'},
    {'left': u'virus', 'right': u'voyager'},
    {'left': u'vulcan', 'right': u'warranty'},
    {'left': u'waffle', 'right': u'waterloo'},
    {'left': u'wallet', 'right': u'whimsical'},
    {'left': u'watchword', 'right': u'wichita'},
    {'left': u'wayside', 'right': u'wilmington'},
    {'left': u'willow', 'right': u'wyoming'},
    {'left': u'woodlark', 'right': u'yesteryear'},
    {'left': u'zulu', 'right': u'yucatan'},
    ]

keys = ["left","right"] * 4
punchars='`~!@#$%^&*()-_=+[{]};:,<.>/?'

def usage(errcode):
    if errcode != 0:
        fd = sys.stderr.fileno()
    else:
        fd = sys.stdout.fileno()
    msg = "usage: pwgen [--nopunc|--punchars=<chars>] [--nospaces]\n"
    os.write(fd, msg.encode('utf8'))
    sys.exit(errcode)

if __name__ == '__main__':
    punc = True
    spaces = True
    skiplist=[]

    for x in range(1,len(sys.argv)):
        if x in skiplist:
            continue
        arg = sys.argv[x]
        if arg == '--usage' or arg == '--help' or \
           arg == '-?' or arg == '-h':
            usage(0)
        elif arg == '--nopunc':
            punc = False
        elif arg.startswith('--punchars'):
            try:
                if len(arg) == len('--punchars'):
                    x+=1
                    skiplist+=[x,]
                    punchars=sys.argv[x]
                else:
                    punchars=arg[len('--punchars')+1:]
                if len(punchars) < 1:
                    msg = "pwgen: error: --punchars=<chars> may not be empty\n"
                    os.write(sys.stderr.fileno(), msg.encode('utf8'))
                    usage(1)
            except IndexError:
                    usage(1)
        elif arg == '--nospaces':
            spaces = False
        else:
            msg = "Unknown argument '%s'\n" % (arg,)
            os.write(sys.stderr.fileno(), msg.encode('utf8'))
            usage(1)
    if punc:
        puncbytes = int(len(punchars) / 256)
        if len(punchars)/256 != 0:
            puncbytes += 1
        extralen = 5 + puncbytes

    # make sure there's some entropy at all...
    try:
        avail = open("/proc/sys/kernel/random/entropy_avail", "r").readline()
        avail = int(avail.strip())
    except Exception:
        os.write(sys.stderr.fileno(),
                 "Could not get available entropy: %s\n" % (x,))
        sys.exit(2)

    if avail < 256:
        os.write(sys.stderr.fileno(), "Not enough entropy available\n")
        sys.exit(3)

    # get enough of it or just error
    try:
        fd = os.open("/dev/random", os.O_RDONLY|os.O_SYNC|os.O_NONBLOCK)
        data = os.read(fd, 8)
        if punc:
            extrabytes = os.read(fd, extralen)
        os.close(fd)
    except Exception:
        os.write(sys.stderr.fileno(), "Could not get random bytes\n")
        sys.exit(4)

    if punc:
        charoffset = extrabytes[0] % 8
        numoffset = extrabytes[1] % 8
        num = extrabytes[2] % 10
        poundoffset = extrabytes[3] % 8
        puncoffset = extrabytes[4] % 8
        punc_encoded = extrabytes[5:]
        decoder = "B" * puncbytes
        punc_encoded = struct.unpack(decoder, punc_encoded)
        puncidx = 0
        for x in range(0, len(punc_encoded)):
            puncidx <<= 8
            puncidx |= punc_encoded[x]
        puncidx %= len(punchars)

    # be sure and tell the user what we got.
    stdout = sys.stdout.fileno()
    for x in range(0, 8):
        if x != 0 and spaces:
            os.write(stdout, ' '.encode('utf8'))
        if punc:
            if poundoffset == x:
                os.write(stdout, '#'.encode('utf8'))
        key = keys[x]
        datum = data[x]
        wordpair = words[datum]
        word = wordpair[key]
        os.write(stdout, word.encode('utf8'))
        if punc:
            if numoffset == x:
                num = "0123456789"[num]
                os.write(stdout, num.encode('utf8'))
            if puncoffset == x:
                val = punchars[puncidx]
                os.write(stdout, val.encode('utf8'))
    os.write(stdout, '\n'.encode('utf8'))
